# Generated by Django 2.2.5 on 2023-07-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_user', '0003_auto_20230708_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchcard',
            name='out',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='rfid_uid',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
